### PR TITLE
Updated DiscordDM userApps & polls status (Update libs.ts)

### PR DESCRIPTION
**Pull request by Suhaybu**
Updated DiscordBM userApps status from 'No' -> 'Has a PR'

edit after @MCausc78's reply:
Updated DiscordBM polls status from 'No' -> 'Has a PR'
Reference: [DiscordBM/DiscordBM#71](https://github.com/DiscordBM/DiscordBM/pull/71)

final edit after @MahdiBM's reply:
Updated DiscordBM userApps & polls status from 'No' -> 'Yes'
Reference: [DiscordBM v1.11.0 release](https://github.com/DiscordBM/DiscordBM/releases/tag/v1.11.0)

### CODE REVIEW

**Comment by Suhaybu** [comment]
> polls were added as well [DiscordBM/DiscordBM#71](https://github.com/DiscordBM/DiscordBM/pull/71)

Oh thank you! Updated the commit

**Comment by MahdiBM** [comment]
I've merged the PR and it'll be in a stable release till the next weekend 🙂

**Comment by MahdiBM** [comment]
Released: https://github.com/DiscordBM/DiscordBM/releases/tag/v1.11.0

**Review by Suhaybu — COMMENTED** [review]
Added userApps and polls in Discord BM
 
 https://github.com/DiscordBM/DiscordBM/releases/tag/v1.11.0

**Pull request merged**
