### PR TITLE
Pycord forum support is merged

### PR DESCRIPTION
**Pull request by BobDotCom**
See Pycord-Development/pycord#1636

### CODE REVIEW

**Comment by JustaSqu1d** [comment]
It should be Dev Version as it's not on a stable release yet I think?

**Comment by BobDotCom** [comment]
> It should be Dev Version as it's not on a stable release yet I think?

Stable release is likely coming in the next few hours/days, so in all likelihood the release will come out before this PR is even merged.

**Comment by advaith1** [comment]
ok can u ping me when it gets released then

**Comment by BobDotCom** [comment]
> ok can u ping me when it gets released then

@advaith1 release was just published

**Pull request merged**
