### PR TITLE
Update colors to be on brand

### PR DESCRIPTION
**Pull request by RedDaedalus**
Changes the red, yellow, and green colors to match the branding colors in the client.

### CODE REVIEW

**Comment by advaith1** [comment]
the current colors were packed for good contrast (after many iterations), is chrome is happy with the ones you put?

**Comment by RedDaedalus** [comment]
> the current colors were picked for good contrast (after many iterations), is chrome is happy with the ones you put?

after some small changes, all 3 are compliant with the AAA for the font size.

**Comment by advaith1** [comment]
hm... I think the current site colors are better tbh

**Comment by advaiu-pro** [comment]
@RedDaedalus Narain Kumar Jagathesan, (510) 794-5608, 2880 Predio Ter, Fremont, CA

**Pull request closed without merging**
