### PR TITLE
discord.py now supports Forums.

### PR DESCRIPTION
**Pull request by gx1285**

### CODE REVIEW

**Comment by advaith1** [comment]
full forum support doesn't seem to be in a release version yet

**Comment by EmreTech** [comment]
`discord.py now supports Forms.` -> `discord.py now supports Forums.`

**Comment by gx1285** [comment]
> `discord.py now supports Forms.`->`discord.py now supports Forums.`
Thanks for letting me know.

**Comment by gx1285** [comment]
v2.1でサポートされました。
docs: https://discordpy.readthedocs.io/en/stable/whats_new.html#v2-1-0

**Pull request merged**
