### PR TITLE
Remora.Discord

### PR DESCRIPTION
**Pull request by xHyroM**

### CODE REVIEW

**Comment by advaith1** [comment]
looks like the last release was in december 2020, so a lot of these are only present in dev versions

**Comment by xHyroM** [comment]
> looks like the last release was in december 2020, so a lot of these are only present in dev versions

Okay, I'll change everything to Dev Version

**Comment by advaith1** [comment]
not everything, just the ones that are in master but not released

**Comment by xHyroM** [comment]
> not everything, just the ones that are in master but not released

done

**Pull request merged**
