### PR TITLE
Add Twilight

### PR DESCRIPTION
**Pull request by Leastrio**

### CODE REVIEW

**Comment by advaith1** [comment]
Twilight doesn't seem to support guild stickers

**Comment by Leastrio** [comment]
I found docs about stickers here: https://api.twilight.rs/twilight/index.html?search=Sticker

**Comment by advaith1** [comment]
that's for receiving stickers in messages, not for guild sticker management/events

**Comment by Leastrio** [comment]
Ah I see, Ill go search for any info about guild stickers

**Comment by Leastrio** [comment]
I just found an issue for it, should I make a commit to show that?

**Comment by advaith1** [comment]
if there's no PR then I think "no" is fine

**Comment by Leastrio** [comment]
Just checked, no pr yet. You're good to merge this then.

**Comment by advaith1** [comment]
looks like this is a bit outdated now but the fork was deleted, it'll be added in #14 instead

**Pull request closed without merging**
