### PR TITLE
Seyfert fully supports User Apps.

### PR DESCRIPTION
**Pull request by uhidontkno**
User apps can be implemented into Seyfert using this example:
```ts
// code example
@Declare({
  name: 'ping',
  description: 'Application ping',
  // now the command can be used in the bot's dm, in a guild and in a group dm (only if the user has installed the "bot application")
  contexts: ['BOT_DM', 'GUILD', 'PRIVATE_CHANNEL'],
  // now the command can be installed in guilds and users
  integrationTypes: ['GUILD_INSTALL', 'USER_INSTALL']
})
class Ping {
  run(ctx: CommandContext) {
    return ctx.write({
      content: 'Pong'
    });
  }
}
```

### CODE REVIEW

**Comment by yosoof3** [comment]
someone should merge this

**Comment by uhidontkno** [comment]
> someone should merge this

real

**Comment by advaith1** [comment]
looks like seyfert doesn't support all of the changes included with the user apps update, e.g. the `authorizing_integration_owners` field. cc @MCausc78

**Comment by uhidontkno** [comment]
> looks like seyfert doesn't support all of the changes included with the user apps update, e.g. the `authorizing_integration_owners` field. cc @MCausc78 

Ah ok

**Comment by uhidontkno** [comment]
I'll close this for now

**Pull request closed without merging**
